title: Save the shark
hero_image: images/banner.png
description: Create a game to save the shark from plastic pollution and improve its health
version: 4
listed: false
copyedit: false
last_tested: "2020-08-17"
steps:
  - title: Introduction
  - title: Move the shark
  - title: Add plastic waste
  - title: Monitor the shark's health
  - title: Feed the shark
  - title: Share your project
  - title: What next?
