---
title: సొరచేపను రక్షించండి
hero_image: images/banner.png
description: ప్లాస్టిక్ కాలుష్యం నుండి సొరచేపని రక్షించడానికి మరియు దాని ఆరోగ్యాన్ని
  మెరుగుపరచడానికి గేమ్‌ను రూపొందించండి
version: 4
listed: true
copyedit: false
last_tested: '2020-08-17'
steps:
- title: పరిచయం
- title: సొరచేపని తరలించండి
- title: ప్లాస్టిక్ వ్యర్థాలను జోడించండి
  completion:
  - engaged
- title: సొరచేప ఆరోగ్యాన్ని పర్యవేక్షించండి
- title: సొరచేపకు ఆహారం ఇవ్వండి
  completion:
  - internal
- title: మీ ప్రాజెక్ట్‌ను అప్‌గ్రేడ్ చేయండి